# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZUWzmjiQ02_opVm1luW92ZlhjEgQFLAs
"""

import streamlit as st
import pandas as pd
import numpy as np
import kagglehub
import os

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score


# --------------------------
# Load Dataset
# --------------------------

@st.cache_data
def load_data():

    path = kagglehub.dataset_download(
        "dhirajnirne/california-housing-data"
    )

    csv_file = [f for f in os.listdir(path) if f.endswith(".csv")][0]

    df = pd.read_csv(os.path.join(path, csv_file))

    df = pd.get_dummies(df, drop_first=True)
    df = df.dropna()

    return df


df = load_data()


# --------------------------
# Train Model
# --------------------------

X = df.drop("median_house_value", axis=1)
y = df["median_house_value"]


@st.cache_resource
def train_model():

    X_train, X_test, y_train, y_test = train_test_split(
        X,
        y,
        test_size=0.2,
        random_state=42
    )

    model = RandomForestRegressor(
        n_estimators=200,
        max_depth=20,
        random_state=42,
        n_jobs=-1
    )

    model.fit(X_train, y_train)

    return model


rf = train_model()


# --------------------------
# Streamlit Interface
# --------------------------

st.title("California Housing Price Predictor")
st.write("Random Forest Regression Model")


st.subheader("Enter House Information")


input_values = []

for feature in X.columns:

    value = st.number_input(
        feature,
        value=float(X[feature].mean())
    )

    input_values.append(value)


# Prediction Button

if st.button("Predict Price"):

    input_array = np.array([input_values])

    prediction = rf.predict(input_array)

    st.success(
        f"Predicted House Value: ${prediction[0]:,.2f}"
    )


# --------------------------
# Feature Importance
# --------------------------

st.subheader("Top Important Features")


importance = pd.Series(
    rf.feature_importances_,
    index=X.columns
).sort_values(ascending=False)


st.bar_chart(
    importance.head(10)
)