# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZUWzmjiQ02_opVm1luW92ZlhjEgQFLAs
"""

import streamlit as st
import numpy as np
import pandas as pd
import joblib


model = joblib.load("random_forest_model.pkl")
features = joblib.load("features.pkl")


st.title("California Housing Price Predictor")


input_data = []

for feature in features:
    value = st.number_input(
        feature,
        value=0.0
    )
    input_data.append(value)


if st.button("Predict"):

    prediction = model.predict(
        np.array([input_data])
    )

    st.success(
        f"Predicted House Value: ${prediction[0]:,.2f}"
    )